# Use Node image
FROM node:18

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy project files
COPY . .

# Build React app
RUN npm run build

# Install serve to host production build
RUN npm install -g serve

# Expose port
EXPOSE 5173

# Start app
CMD ["serve", "-s", "dist", "-l", "5173"]
